#!/bin/bash

cd `dirname $0`

classpath="./conf:./lib/*:./bin:/home/lneves/Work/ActiveProjects/sapo/BrokerV4/BrokerPublicRepo/sapo-broker/lib/*"


java -server \
-Xverify:none -Xms16M -Xmx32M \
-Djava.awt.headless=true \
-Djava.net.preferIPv4Stack=true \
-Djava.net.preferIPv6Addresses=false \
-Dfile.encoding=UTF-8 \
-cp $classpath \
pt.com.broker.jsbridge.JSBridgeServer
