//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.04 at 02:15:11 PM WET 
//

package pt.com.broker.jsbridge.configuration;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the pt.com.broker.jsbridge.configuration package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.com.broker.jsbridge.configuration
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link BridgeConfiguration.Settings }
	 * 
	 */
	public BridgeConfiguration.Settings createBridgeConfigurationSettings()
	{
		return new BridgeConfiguration.Settings();
	}

	/**
	 * Create an instance of {@link BridgeConfiguration.Channels }
	 * 
	 */
	public BridgeConfiguration.Channels createBridgeConfigurationChannels()
	{
		return new BridgeConfiguration.Channels();
	}

	/**
	 * Create an instance of {@link BridgeConfiguration.Settings.DefaultBroker }
	 * 
	 */
	public BridgeConfiguration.Settings.DefaultBroker createBridgeConfigurationSettingsDefaultBroker()
	{
		return new BridgeConfiguration.Settings.DefaultBroker();
	}

	/**
	 * Create an instance of {@link BridgeConfiguration }
	 * 
	 */
	public BridgeConfiguration createBridgeConfiguration()
	{
		return new BridgeConfiguration();
	}

	/**
	 * Create an instance of {@link BridgeConfiguration.Settings.Bridge }
	 * 
	 */
	public BridgeConfiguration.Settings.Bridge createBridgeConfigurationSettingsBridge()
	{
		return new BridgeConfiguration.Settings.Bridge();
	}

	/**
	 * Create an instance of {@link BridgeConfiguration.Channels.Channel }
	 * 
	 */
	public BridgeConfiguration.Channels.Channel createBridgeConfigurationChannelsChannel()
	{
		return new BridgeConfiguration.Channels.Channel();
	}

}
