/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package pt.com.broker.codec.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;
public enum ActionType implements TEnum{
    PUBLISH(0),
    POLL(1),
    ACCEPTED(2),
    ACKNOWLEDGE(3),
    SUBSCRIBE(4),
    UNSUBSCRIBE(5),
    NOTIFICATION(6),
    FAULT(7),
    PING(8),
    PONG(9),
    AUTH(10);

  private static final Map<Integer, ActionType> BY_VALUE = new HashMap<Integer,ActionType>() {{
    for(ActionType val : ActionType.values()) {
      put(val.getValue(), val);
    }
  }};

  private final int value;

  private ActionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ActionType findByValue(int value) { 
    return BY_VALUE.get(value);
  }
}
