/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package pt.com.broker.codec.thrift;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;

public class AuthMessageType {
  public static final int CLIENT_AUTH = 0;
  public static final int SERVER_CHALLENGE = 1;
  public static final int SERVER_CHALLENGE_RESPONSE_CLIENT_CHALLENGE = 2;
  public static final int CLIENT_CHALLENGE_RESPONSE = 3;
  public static final int CLIENT_ACKNOWLEDGE = 4;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(CLIENT_AUTH, SERVER_CHALLENGE, SERVER_CHALLENGE_RESPONSE_CLIENT_CHALLENGE, CLIENT_CHALLENGE_RESPONSE, CLIENT_ACKNOWLEDGE);
}
