/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package pt.com.broker.codec.thrift;


import java.util.Set;
import java.util.HashSet;
import java.util.Collections;
import org.apache.thrift.IntRangeSet;
import java.util.Map;
import java.util.HashMap;

public class DestinationType {
  public static final int TOPIC = 0;
  public static final int QUEUE = 1;
  public static final int VIRTUAL_QUEUE = 2;

  public static final IntRangeSet VALID_VALUES = new IntRangeSet(TOPIC, QUEUE, VIRTUAL_QUEUE);
  public static final Map<Integer, String> VALUES_TO_NAMES = new HashMap<Integer, String>() {{
    put(TOPIC, "TOPIC");
    put(QUEUE, "QUEUE");
    put(VIRTUAL_QUEUE, "VIRTUAL_QUEUE");
  }};
}
