/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pt.com.broker.codec.thrift;

import java.util.BitSet;
import java.util.Collections;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.Map;

import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

class Atom implements org.apache.thrift.TBase<Atom, Atom._Fields>, java.io.Serializable, Cloneable, Comparable<Atom>
{
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Atom");

	private static final org.apache.thrift.protocol.TField HEADER_FIELD_DESC = new org.apache.thrift.protocol.TField("header", org.apache.thrift.protocol.TType.STRUCT, (short) 1);
	private static final org.apache.thrift.protocol.TField ACTION_FIELD_DESC = new org.apache.thrift.protocol.TField("action", org.apache.thrift.protocol.TType.STRUCT, (short) 2);

	private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
	static
	{
		schemes.put(StandardScheme.class, new AtomStandardSchemeFactory());
		schemes.put(TupleScheme.class, new AtomTupleSchemeFactory());
	}

	public Header header; // optional
	public Action action; // required

	/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum
	{
		HEADER((short) 1, "header"),
		ACTION((short) 2, "action");

		private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

		static
		{
			for (_Fields field : EnumSet.allOf(_Fields.class))
			{
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not found.
		 */
		public static _Fields findByThriftId(int fieldId)
		{
			switch (fieldId)
			{
			case 1: // HEADER
				return HEADER;
			case 2: // ACTION
				return ACTION;
			default:
				return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId)
		{
			_Fields fields = findByThriftId(fieldId);
			if (fields == null)
				throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not found.
		 */
		public static _Fields findByName(String name)
		{
			return byName.get(name);
		}

		private final short _thriftId;
		private final String _fieldName;

		_Fields(short thriftId, String fieldName)
		{
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId()
		{
			return _thriftId;
		}

		public String getFieldName()
		{
			return _fieldName;
		}
	}

	// isset id assignments
	private _Fields optionals[] = { _Fields.HEADER };
	public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
	static
	{
		Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
		tmpMap.put(_Fields.HEADER, new org.apache.thrift.meta_data.FieldMetaData("header", org.apache.thrift.TFieldRequirementType.OPTIONAL,
				new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Header.class)));
		tmpMap.put(_Fields.ACTION, new org.apache.thrift.meta_data.FieldMetaData("action", org.apache.thrift.TFieldRequirementType.DEFAULT,
				new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Action.class)));
		metaDataMap = Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Atom.class, metaDataMap);
	}

	public Atom()
	{
	}

	public Atom(
			Action action)
	{
		this();
		this.action = action;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public Atom(Atom other)
	{
		if (other.isSetHeader())
		{
			this.header = new Header(other.header);
		}
		if (other.isSetAction())
		{
			this.action = new Action(other.action);
		}
	}

	public Atom deepCopy()
	{
		return new Atom(this);
	}

	@Override
	public void clear()
	{
		this.header = null;
		this.action = null;
	}

	public Header getHeader()
	{
		return this.header;
	}

	public Atom setHeader(Header header)
	{
		this.header = header;
		return this;
	}

	public void unsetHeader()
	{
		this.header = null;
	}

	/** Returns true if field header is set (has been assigned a value) and false otherwise */
	public boolean isSetHeader()
	{
		return this.header != null;
	}

	public void setHeaderIsSet(boolean value)
	{
		if (!value)
		{
			this.header = null;
		}
	}

	public Action getAction()
	{
		return this.action;
	}

	public Atom setAction(Action action)
	{
		this.action = action;
		return this;
	}

	public void unsetAction()
	{
		this.action = null;
	}

	/** Returns true if field action is set (has been assigned a value) and false otherwise */
	public boolean isSetAction()
	{
		return this.action != null;
	}

	public void setActionIsSet(boolean value)
	{
		if (!value)
		{
			this.action = null;
		}
	}

	public void setFieldValue(_Fields field, Object value)
	{
		switch (field)
		{
		case HEADER:
			if (value == null)
			{
				unsetHeader();
			}
			else
			{
				setHeader((Header) value);
			}
			break;

		case ACTION:
			if (value == null)
			{
				unsetAction();
			}
			else
			{
				setAction((Action) value);
			}
			break;

		}
	}

	public Object getFieldValue(_Fields field)
	{
		switch (field)
		{
		case HEADER:
			return getHeader();

		case ACTION:
			return getAction();

		}
		throw new IllegalStateException();
	}

	/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
	public boolean isSet(_Fields field)
	{
		if (field == null)
		{
			throw new IllegalArgumentException();
		}

		switch (field)
		{
		case HEADER:
			return isSetHeader();
		case ACTION:
			return isSetAction();
		}
		throw new IllegalStateException();
	}

	@Override
	public boolean equals(Object that)
	{
		if (that == null)
			return false;
		if (that instanceof Atom)
			return this.equals((Atom) that);
		return false;
	}

	public boolean equals(Atom that)
	{
		if (that == null)
			return false;

		boolean this_present_header = true && this.isSetHeader();
		boolean that_present_header = true && that.isSetHeader();
		if (this_present_header || that_present_header)
		{
			if (!(this_present_header && that_present_header))
				return false;
			if (!this.header.equals(that.header))
				return false;
		}

		boolean this_present_action = true && this.isSetAction();
		boolean that_present_action = true && that.isSetAction();
		if (this_present_action || that_present_action)
		{
			if (!(this_present_action && that_present_action))
				return false;
			if (!this.action.equals(that.action))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode()
	{
		return 0;
	}

	@Override
	public int compareTo(Atom other)
	{
		if (!getClass().equals(other.getClass()))
		{
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = Boolean.valueOf(isSetHeader()).compareTo(other.isSetHeader());
		if (lastComparison != 0)
		{
			return lastComparison;
		}
		if (isSetHeader())
		{
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.header, other.header);
			if (lastComparison != 0)
			{
				return lastComparison;
			}
		}
		lastComparison = Boolean.valueOf(isSetAction()).compareTo(other.isSetAction());
		if (lastComparison != 0)
		{
			return lastComparison;
		}
		if (isSetAction())
		{
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.action, other.action);
			if (lastComparison != 0)
			{
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId)
	{
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException
	{
		schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException
	{
		schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("Atom(");
		boolean first = true;

		if (isSetHeader())
		{
			sb.append("header:");
			if (this.header == null)
			{
				sb.append("null");
			}
			else
			{
				sb.append(this.header);
			}
			first = false;
		}
		if (!first)
			sb.append(", ");
		sb.append("action:");
		if (this.action == null)
		{
			sb.append("null");
		}
		else
		{
			sb.append(this.action);
		}
		first = false;
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException
	{
		// check for required fields
		// check for sub-struct validity
		if (header != null)
		{
			header.validate();
		}
		if (action != null)
		{
			action.validate();
		}
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException
	{
		try
		{
			write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
		}
		catch (org.apache.thrift.TException te)
		{
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException
	{
		try
		{
			read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
		}
		catch (org.apache.thrift.TException te)
		{
			throw new java.io.IOException(te);
		}
	}

	private static class AtomStandardSchemeFactory implements SchemeFactory
	{
		public AtomStandardScheme getScheme()
		{
			return new AtomStandardScheme();
		}
	}

	private static class AtomStandardScheme extends StandardScheme<Atom>
	{

		public void read(org.apache.thrift.protocol.TProtocol iprot, Atom struct) throws org.apache.thrift.TException
		{
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true)
			{
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP)
				{
					break;
				}
				switch (schemeField.id)
				{
				case 1: // HEADER
					if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT)
					{
						struct.header = new Header();
						struct.header.read(iprot);
						struct.setHeaderIsSet(true);
					}
					else
					{
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				case 2: // ACTION
					if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT)
					{
						struct.action = new Action();
						struct.action.read(iprot);
						struct.setActionIsSet(true);
					}
					else
					{
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					break;
				default:
					org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();

			// check for required fields of primitive type, which can't be checked in the validate method
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, Atom struct) throws org.apache.thrift.TException
		{
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.header != null)
			{
				if (struct.isSetHeader())
				{
					oprot.writeFieldBegin(HEADER_FIELD_DESC);
					struct.header.write(oprot);
					oprot.writeFieldEnd();
				}
			}
			if (struct.action != null)
			{
				oprot.writeFieldBegin(ACTION_FIELD_DESC);
				struct.action.write(oprot);
				oprot.writeFieldEnd();
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class AtomTupleSchemeFactory implements SchemeFactory
	{
		public AtomTupleScheme getScheme()
		{
			return new AtomTupleScheme();
		}
	}

	private static class AtomTupleScheme extends TupleScheme<Atom>
	{

		@Override
		public void write(org.apache.thrift.protocol.TProtocol prot, Atom struct) throws org.apache.thrift.TException
		{
			TTupleProtocol oprot = (TTupleProtocol) prot;
			BitSet optionals = new BitSet();
			if (struct.isSetHeader())
			{
				optionals.set(0);
			}
			if (struct.isSetAction())
			{
				optionals.set(1);
			}
			oprot.writeBitSet(optionals, 2);
			if (struct.isSetHeader())
			{
				struct.header.write(oprot);
			}
			if (struct.isSetAction())
			{
				struct.action.write(oprot);
			}
		}

		@Override
		public void read(org.apache.thrift.protocol.TProtocol prot, Atom struct) throws org.apache.thrift.TException
		{
			TTupleProtocol iprot = (TTupleProtocol) prot;
			BitSet incoming = iprot.readBitSet(2);
			if (incoming.get(0))
			{
				struct.header = new Header();
				struct.header.read(iprot);
				struct.setHeaderIsSet(true);
			}
			if (incoming.get(1))
			{
				struct.action = new Action();
				struct.action.read(iprot);
				struct.setActionIsSet(true);
			}
		}
	}

}
