//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 02:24:03 PM WEST 
//

package pt.com.gcs.conf.global;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Agents complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Agents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="agent" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="agent-policy">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="policy-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="agent-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Agents", propOrder = { "agent" })
public class Agents
{

	@XmlElement(required = true)
	protected List<Agents.Agent> agent;

	/**
	 * Gets the value of the agent property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the agent property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAgent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Agents.Agent }
	 * 
	 * 
	 */
	public List<Agents.Agent> getAgent()
	{
		if (agent == null)
		{
			agent = new ArrayList<Agents.Agent>();
		}
		return this.agent;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="agent-policy">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="policy-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="agent-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "agentPolicy" })
	public static class Agent
	{

		@XmlElement(name = "agent-policy", required = true)
		protected Agents.Agent.AgentPolicy agentPolicy;
		@XmlAttribute(name = "agent-name", required = true)
		protected String agentName;

		/**
		 * Gets the value of the agentPolicy property.
		 * 
		 * @return possible object is {@link Agents.Agent.AgentPolicy }
		 * 
		 */
		public Agents.Agent.AgentPolicy getAgentPolicy()
		{
			return agentPolicy;
		}

		/**
		 * Sets the value of the agentPolicy property.
		 * 
		 * @param value
		 *            allowed object is {@link Agents.Agent.AgentPolicy }
		 * 
		 */
		public void setAgentPolicy(Agents.Agent.AgentPolicy value)
		{
			this.agentPolicy = value;
		}

		/**
		 * Gets the value of the agentName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAgentName()
		{
			return agentName;
		}

		/**
		 * Sets the value of the agentName property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAgentName(String value)
		{
			this.agentName = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="policy-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class AgentPolicy
		{

			@XmlAttribute(name = "policy-name", required = true)
			protected String policyName;

			/**
			 * Gets the value of the policyName property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getPolicyName()
			{
				return policyName;
			}

			/**
			 * Sets the value of the policyName property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setPolicyName(String value)
			{
				this.policyName = value;
			}

		}

	}

}
