//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 02:24:03 PM WEST 
//

package pt.com.gcs.conf.global;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BrokerSecurityPolicy complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BrokerSecurityPolicy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policies" type="{}Policies" minOccurs="0"/>
 *         &lt;element name="agents" type="{}Agents" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BrokerSecurityPolicy", propOrder = { "policies", "agents" })
public class BrokerSecurityPolicy
{

	protected Policies policies;
	protected Agents agents;

	/**
	 * Gets the value of the policies property.
	 * 
	 * @return possible object is {@link Policies }
	 * 
	 */
	public Policies getPolicies()
	{
		return policies;
	}

	/**
	 * Sets the value of the policies property.
	 * 
	 * @param value
	 *            allowed object is {@link Policies }
	 * 
	 */
	public void setPolicies(Policies value)
	{
		this.policies = value;
	}

	/**
	 * Gets the value of the agents property.
	 * 
	 * @return possible object is {@link Agents }
	 * 
	 */
	public Agents getAgents()
	{
		return agents;
	}

	/**
	 * Sets the value of the agents property.
	 * 
	 * @param value
	 *            allowed object is {@link Agents }
	 * 
	 */
	public void setAgents(Agents value)
	{
		this.agents = value;
	}

}
