//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.10 at 05:51:46 PM WEST 
//

package pt.com.broker.performance.distributed.conf;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the pt.com.broker.performance.distributed.conf package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.com.broker.performance.distributed.conf
	 * 
	 */
	public ObjectFactory()
	{
	}

	/**
	 * Create an instance of {@link Consumers.Consumer }
	 * 
	 */
	public Consumers.Consumer createConsumersConsumer()
	{
		return new Consumers.Consumer();
	}

	/**
	 * Create an instance of {@link Machines.Machine }
	 * 
	 */
	public Machines.Machine createMachinesMachine()
	{
		return new Machines.Machine();
	}

	/**
	 * Create an instance of {@link Producers.Producer }
	 * 
	 */
	public Producers.Producer createProducersProducer()
	{
		return new Producers.Producer();
	}

	/**
	 * Create an instance of {@link Tests.Test }
	 * 
	 */
	public Tests.Test createTestsTest()
	{
		return new Tests.Test();
	}

	/**
	 * Create an instance of {@link TestConfiguration }
	 * 
	 */
	public TestConfiguration createTestConfiguration()
	{
		return new TestConfiguration();
	}

	/**
	 * Create an instance of {@link Consumers }
	 * 
	 */
	public Consumers createConsumers()
	{
		return new Consumers();
	}

	/**
	 * Create an instance of {@link Tests.Test.Destination }
	 * 
	 */
	public Tests.Test.Destination createTestsTestDestination()
	{
		return new Tests.Test.Destination();
	}

	/**
	 * Create an instance of {@link Producers }
	 * 
	 */
	public Producers createProducers()
	{
		return new Producers();
	}

	/**
	 * Create an instance of {@link Machines }
	 * 
	 */
	public Machines createMachines()
	{
		return new Machines();
	}

	/**
	 * Create an instance of {@link Tests.Test.Messages }
	 * 
	 */
	public Tests.Test.Messages createTestsTestMessages()
	{
		return new Tests.Test.Messages();
	}

	/**
	 * Create an instance of {@link Tests }
	 * 
	 */
	public Tests createTests()
	{
		return new Tests();
	}

	/**
	 * Create an instance of {@link Agents }
	 * 
	 */
	public Agents createAgents()
	{
		return new Agents();
	}

	/**
	 * Create an instance of {@link Agents.Agent }
	 * 
	 */
	public Agents.Agent createAgentsAgent()
	{
		return new Agents.Agent();
	}

}
